apiVersion: v1
kind: ConfigMap
metadata:
    name: caretta-grafana-datasources
    namespace: {{ .Release.Namespace }}
data:
 automatic.yml: |
    datasources:
    - name: Prometheus
      # <string, required> datasource type. Required
      type: prometheus
      # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
      access: proxy
      # <int> org id. will default to orgId 1 if not specified
      orgId: 1
      # <string> custom UID which can be used to reference this datasource in other parts of the configuration, if not specified will be generated automatically
      uid: 
      # <string> url
      url: http://prometheus:9090
      # <string> database user, if used
      user:
      # <string> database name, if used
      database:
      # <bool> enable/disable basic auth
      basicAuth:
      # <string> basic auth username
      basicAuthUser:
      # <bool> enable/disable with credentials headers
      withCredentials:
      # <bool> mark as default datasource. Max one per org
      isDefault:
      # <map> fields that will be converted to json and stored in jsonData
      jsonData:
        graphiteVersion: '1.1'
        tlsAuth: true
        tlsAuthWithCACert: true
      # <string> json object of data that will be encrypted.
      secureJsonData:
        tlsCACert: '...'
        tlsClientCert: '...'
        tlsClientKey: '...'
        # <string> database password, if used
        password:
        # <string> basic auth password
        basicAuthPassword:
      version: 1
      # <bool> allow users to edit datasources from the UI.
      editable: false
