name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      -
        name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: go.mod
          cache-dependency-path: go.sum
      -
        name: Install Dependencies
        run: |
          make generate_ebpf_in_docker
          go mod download -x
      -
        name: Build Binary
        run: make build
      -
        name: Build & Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: quay.io/groundcover/caretta:${{ github.ref_name	 }}
          platforms: linux/amd64,linux/arm64
      -
        name: Checkout Helm Repo
        uses: actions/checkout@v3
        with:
          path: helm-repo
          repository: groundcover-com/charts
          token: ${{ secrets.HELM_CHARTS_REPO_KEY }}
      -
        name: Publish Chart
        working-directory: helm-repo
        env:
          GITHUB_TAG: ${{ github.ref_name	 }}
        run: |
          version=${GITHUB_TAG#v}
          helm lint ../chart
          helm package --version ${version} --app-version ${GITHUB_TAG} ../chart
          helm repo index --url https://helm.groundcover.com .
          git config user.name "ci-groundcover"
          git config user.email "ci@groundcover.com"
          git add .
          git commit -m "Added caretta ${version} chart"
          git push
